### ISSUE TITLE
Anticipated martyrology

### ISSUE THREAD

**Issue by benstox** [veromary/roman-martyrology#4]
Thanks for all your work on this. I've found it really useful. Have you considered giving the anticipated martyrology as the default on page, as you would recite at the office of Prime? So that if I visit the page today I get the martyrology of tomorrow's feast by default?

**Comment by veromary** [comment]
I have thought about it - it makes sense as the most usual case would be for people saying Prime rather than finding the Saints of the Day - there are other websites for that.

Wondering about the technicalities though - the javascript widget from rotate content can be duplicated and adjusted. I'm not great at this, but there was some code for working out the Next Day for the forward and back buttons on each day's page, so should be fairly straightforward to apply that to the front page.

**Comment by veromary** [comment]
The Next button on each day's page uses liquid to link the next page rather than Javascript.

So far I've made a link to the day's page, then there's a link to tomorrow's reading at the bottom right.

Making a link to the anticipated Martyrology from the front page might be the next step. Most cases are alright - just the end of each month and leap years to consider.

**Comment by veromary** [comment]
I might close this. Now the front page says today's date, with a link to today's saints, followed by the anticipated martyrology text.
